name: Github Workflows Angular with NPM

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - run: ls
      shell: bash
      
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1

    # - run: | 
    #     npm install --location=global @angular/cli@13.1.3
    #     npm install
    #     ng build
    #   shell: bash

    # - run: |
    #     echo ${{ toJSON(github) }}
    #   shell: bash

    # - run: ng test --no-watch --code-coverage

    # - name: Official SonarQube Scan
    #   uses: SonarSource/sonarqube-scan-action@v1.1.0
    #   env:
    #     SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
    #     SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

    # - name: SonarQube Quality Gate check
    #   uses: sonarsource/sonarqube-quality-gate-action@master
    #   timeout-minutes: 10
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: buildApp
    #     path: ./dist/*/
    #     if-no-files-found: error