name: Github Workflows Spring Boot with Gradle

runs:
  using: "composite"
  steps:

    - run: | 
        echo "ACTION SPRINGBOOT-GRADLE"
      shell: bash


# name: Github Workflows Springboot with Gradle

# on:
#   workflow_call:

# jobs:
#   github-wf-springboot-gradle:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up JDK 17
#         uses: actions/setup-java@v2
#         with:
#           java-version: 17
#           distribution: 'adopt'

#       - name: Make gradlew executable
#         run: chmod +x ./gradlew

#       - name: Build
#         uses: gradle/gradle-build-action@v2.1.5
#         with:
#           arguments: bootJar

#       - name: Test
#         uses: gradle/gradle-build-action@v2.1.5
#         with:
#           arguments: test

#       - name: Official SonarQube Scan
#         uses: SonarSource/sonarqube-scan-action@v1.1.0
#         env:
#           SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
#           SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

#       - name: SonarQube Quality Gate check
#         uses: sonarsource/sonarqube-quality-gate-action@master
#         timeout-minutes: 10
#         env:
#           SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

#       - uses: actions/upload-artifact@v3
#         with:
#           name: buildApp
#           path: ./*/*/*.jar
#           if-no-files-found: error