name: Github Workflows CI Action

on:
  workflow_dispatch:
    inputs:
      APPLICATION_RUNTIME:
        description: 'Specify the core of the solution'
        required: true
        type: string

      BUILD_COMPILE:
        description: 'Specify the build tool of the solution'
        required: true
        type: string

  workflow_call:
    inputs:
      APPLICATION_RUNTIME:
        description: 'Specify the core of the solution'
        required: true
        type: string

      BUILD_COMPILE:
        description: 'Specify the build tool of the solution'
        required: true
        type: string

jobs:
  github-wf-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/angular-npm
        if: ${{ inputs.APPLICATION_RUNTIME == 'angular' && inputs.BUILD_COMPILE == 'npm' }}

      - uses: ./.github/actions/springboot-gradle
        if: ${{ inputs.APPLICATION_RUNTIME == 'springboot' && inputs.BUILD_COMPILE == 'gradle' }}