name: Github Workflows CI Action

on:
  workflow_dispatch:
    inputs:
      APPLICATION_RUNTIME:
        description: 'Specify the core of the solution'
        required: true
        type: string

      BUILD_COMPILE:
        description: 'Specify the build tool of the solution'
        required: true
        type: string

  workflow_call:
    inputs:
      APPLICATION_RUNTIME:
        description: 'Specify the core of the solution'
        required: true
        type: string

      BUILD_COMPILE:
        description: 'Specify the build tool of the solution'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      action_path: ${{ steps.build_step.outputs.action_path }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build_step
        run: echo "::set-output name=action_path::$action_path"

  github-wf-ci:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ inputs.APPLICATION_RUNTIME }}-${{ inputs.BUILD_COMPILE }}
      - run: echo ${{ needs.build.outputs.action_path }}
      # - name: BuildSolution
      #   uses: ./.github/actions/${{ inputs.APPLICATION_RUNTIME }}-${{ inputs.BUILD_COMPILE }}
