name: Github Workflows CI Action

on:
  workflow_call:
    inputs:
      APPLICATION_RUNTIME:
        description: 'Specify the core of the solution'
        required: true
        type: string

      BUILD_COMPILE:
        description: 'Specify the build tool of the solution'
        required: true
        type: string

jobs:
  github-wf-ci:
    runs-on: ubuntu-latest
    steps:
      - id: ci
        uses: rapharw/github-wf-templates/.github/workflows/${{ inputs.APPLICATION_RUNTIME }}-${{ inputs.BUILD_COMPILE }}.yaml