name: Github Workflows CI Action

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      APPLICATION_RUNTIME:
        description: 'Specify the core of the solution'
        required: true
        type: string

      BUILD_COMPILE:
        description: 'Specify the build tool of the solution'
        required: true
        type: string

env:
  ACTION_PATH: ${{ inputs.APPLICATION_RUNTIME }}-${{ inputs.BUILD_COMPILE }}/action.yaml

jobs:
  github-wf-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/${{ env.ACTION_PATH }}
        env:
          ACTION_PATH: ${{ env.ACTION_PATH }}