name: Github Workflows CI Action

on:
  workflow_dispatch:
    inputs:
      APPLICATION_RUNTIME:
        description: 'Specify the technology of the solution'
        required: true
        type: choice
        options:
        - angular
        - springboot

      BUILD_COMPILE:
        description: 'Specify the build tool of the solution'
        required: true
        type: choice
        options:
        - npm
        - gradle

  workflow_call:
    inputs:
      APPLICATION_RUNTIME:
        required: true
        type: string

      BUILD_COMPILE:
        required: true
        type: string

jobs:
  github-wf-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ls
        shell: bash

      - uses: rapharw/github-wf-templates/.github/actions/angular-npm
        if: ${{ inputs.APPLICATION_RUNTIME == 'angular' && inputs.BUILD_COMPILE == 'npm' }}

      - uses: ./.github/actions/springboot-gradle
        if: ${{ inputs.APPLICATION_RUNTIME == 'springboot' && inputs.BUILD_COMPILE == 'gradle' }}