name: Github Workflows CI Action

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      APPLICATION_RUNTIME:
        description: 'Specify the core of the solution'
        required: true
        type: string

      BUILD_COMPILE:
        description: 'Specify the build tool of the solution'
        required: true
        type: string

jobs:
  github-wf-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        uses: ./.github/actions/${{ github.event.inputs.APPLICATION_RUNTIME }}-${{ github.event.inputs.BUILD_COMPILE }}/action.yaml